/// Sample products to populate Firestore for testing
/// 
/// These products match the Product model structure
/// and can be uploaded to Firestore for development/testing

final List<Map<String, dynamic>> sampleProducts = [
  {
    'title': 'Purple Hoodie',
    'price': 25.99,
    'originalPrice': 35.99,
    'imageUrl': 'assets/images/hoodie_purple.jpg',
    'availableColors': ['Purple', 'Black', 'White'],
    'availableSizes': ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    'description': 'Comfortable purple hoodie with University of Portsmouth logo. Perfect for staying warm on campus.',
    'maxStock': 50,
    'category': 'clothing',
  },
  {
    'title': 'Signature T-Shirt',
    'price': 12.99,
    'originalPrice': null,
    'imageUrl': 'assets/images/tshirt_signature.jpg',
    'availableColors': ['Navy', 'Grey', 'White', 'Black'],
    'availableSizes': ['XS', 'S', 'M', 'L', 'XL'],
    'description': 'Classic t-shirt featuring the Union Shop signature design. Made from 100% cotton.',
    'maxStock': 100,
    'category': 'clothing',
  },
  {
    'title': 'Tote Bag',
    'price': 8.99,
    'originalPrice': null,
    'imageUrl': 'assets/images/tote_bag.jpg',
    'availableColors': ['Black', 'Navy', 'Red'],
    'availableSizes': ['One Size'],
    'description': 'Durable canvas tote bag perfect for carrying books and belongings around campus.',
    'maxStock': 75,
    'category': 'merchandise',
  },
  {
    'title': 'Graduation Cap & Gown Bundle',
    'price': 49.99,
    'originalPrice': 59.99,
    'imageUrl': 'assets/images/collections/graduation.jpg',
    'availableColors': ['Black'],
    'availableSizes': ['S', 'M', 'L', 'XL'],
    'description': 'Official graduation cap and gown set for Portsmouth University ceremonies.',
    'maxStock': 30,
    'category': 'graduation',
  },
  {
    'title': 'Personalised Notebook',
    'price': 6.99,
    'originalPrice': null,
    'imageUrl': 'assets/images/collections/personalisation.jpg',
    'availableColors': ['Blue', 'Red', 'Green', 'Purple'],
    'availableSizes': ['A5', 'A4'],
    'description': 'Premium notebook that can be personalised with your name or custom design.',
    'maxStock': 200,
    'category': 'stationery',
  },
  {
    'title': 'Union Shop Water Bottle',
    'price': 15.99,
    'originalPrice': null,
    'imageUrl': 'assets/images/collections/portsmouth.jpg',
    'availableColors': ['Purple', 'White'],
    'availableSizes': ['500ml', '750ml'],
    'description': 'Eco-friendly reusable water bottle with Union Shop branding. Keeps drinks cold for hours.',
    'maxStock': 60,
    'category': 'merchandise',
  },
  {
    'title': 'Pride Flag',
    'price': 9.99,
    'originalPrice': null,
    'imageUrl': 'assets/images/collections/pride.jpg',
    'availableColors': ['Rainbow', 'Trans', 'Non-Binary'],
    'availableSizes': ['Small', 'Medium', 'Large'],
    'description': 'Vibrant pride flag to show your support. Available in multiple pride variations.',
    'maxStock': 40,
    'category': 'pride',
  },
  {
    'title': 'Stationery Bundle Pack',
    'price': 14.99,
    'originalPrice': 19.99,
    'imageUrl': 'assets/images/collections/stationery.jpg',
    'availableColors': ['Assorted'],
    'availableSizes': ['One Size'],
    'description': 'Complete stationery bundle including pens, pencils, highlighters, and sticky notes.',
    'maxStock': 80,
    'category': 'stationery',
  },
  {
    'title': 'Sports Team Jersey',
    'price': 22.99,
    'originalPrice': null,
    'imageUrl': 'assets/images/collections/sports.jpg',
    'availableColors': ['Navy with Gold', 'Black with Silver'],
    'availableSizes': ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    'description': 'Official Portsmouth University sports team jersey. Perfect for fans and athletes.',
    'maxStock': 45,
    'category': 'sports',
  },
  {
    'title': 'Customisable Mug',
    'price': 7.99,
    'originalPrice': null,
    'imageUrl': 'assets/images/collections/print_shack.jpg',
    'availableColors': ['White', 'Black', 'Blue'],
    'availableSizes': ['350ml', '500ml'],
    'description': 'High-quality ceramic mug that can be customised with your own design or text.',
    'maxStock': 120,
    'category': 'personalisation',
  },
];